[package]
name = "groestlcoin"
version = "0.29.0"
authors = ["Groestlcoin Developers <groestlcoin@gmail.com>"]
license = "CC0-1.0"
repository = "https://github.com/Groestlcoin/rust-groestlcoin/"
documentation = "https://docs.rs/groestlcoin/"
description = "General purpose library for using and interoperating with Groestlcoin."
categories = ["cryptography::cryptocurrencies"]
keywords = [ "crypto", "groestlcoin" ]
readme = "README.md"
edition = "2018"
exclude = ["tests", "contrib"]

[features]
default = [ "std", "secp-recovery" ]
rand-std = ["secp256k1/rand-std"]
rand = ["secp256k1/rand"]
serde = ["actual-serde", "groestlcoin_hashes/serde", "secp256k1/serde"]
secp-lowmemory = ["secp256k1/lowmemory"]
secp-recovery = ["secp256k1/recovery"]
groestlcoinconsensus-std = ["groestlcoinconsensus/std", "std"]

# At least one of std, no-std must be enabled.
#
# The no-std feature doesn't disable std - you need to turn off the std feature for that by disabling default.
# Instead no-std enables additional features required for this crate to be usable without std.
# As a result, both can be enabled without conflict.
std = ["secp256k1/std", "groestlcoin_hashes/std", "bech32/std", "groestlcoin-internals/std"]
no-std = ["core2", "groestlcoin_hashes/alloc", "groestlcoin_hashes/core2", "secp256k1/alloc"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
groestlcoin-internals = { path = "../internals" }
bech32 = { version = "0.9.0", default-features = false }
groestlcoin_hashes = { version = "0.11.0", default-features = false }
secp256k1 = { version = "0.25.0", default-features = false } # do not use bitcoin-hashes feature

base64 = { version = "0.13.0", optional = true }
groestlcoinconsensus = { version = "2.20.1-0.5.0", default-features = false, optional = true }
core2 = { version = "0.3.0", default-features = false, features = ["alloc"], optional = true }
# Do NOT use this as a feature! Use the `serde` feature instead.
actual-serde = { package = "serde", version = "1.0.103", default-features = false, features = [ "derive", "alloc" ], optional = true }

[dev-dependencies]
serde_json = "1.0.0"
serde_test = "1.0.19"
serde_derive = "1.0.103"
secp256k1 = { version = "0.25.0", features = ["recovery"] }
bincode = "1.3.1"

[target.'cfg(mutate)'.dev-dependencies]
mutagen = { git = "https://github.com/llogiq/mutagen" }

[[example]]
name = "bip32"

[[example]]
name = "handshake"
required-features = ["std", "rand-std"]

[[example]]
name = "ecdsa-psbt"
required-features = ["std", "groestlcoinconsensus"]

[[example]]
name = "taproot-psbt"
required-features = ["std", "rand-std", "groestlcoinconsensus"]
