[workspace]
members = ["groestlcoin", "hashes", "internals", "fuzz", "io"]
resolver = "2"

[patch.crates-io.groestlcoin]
path = "groestlcoin"

[patch.crates-io.groestlcoin_hashes]
path = "hashes"

[patch.crates-io.groestlcoin-internals]
path = "internals"

[patch.crates-io.bitcoin-io]
path = "io"
