[workspace]
members = ["groestlcoin", "hashes", "internals", "fuzz"]

[patch.crates-io.groestlcoin]
path = "groestlcoin"

[patch.crates-io.groestlcoin_hashes]
path = "hashes"

[patch.crates-io.groestlcoin-internals]
path = "internals"
