on:
  push:
    branches:
      - master
      - v0.28.0
      - v0.29.0
      - v0.30.0
  pull_request:

name: Release

jobs:
  release:
    name: Release - dry-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v4
      - name: Checkout Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: run cargo
        run: contrib/release.sh
